### ISSUE TITLE
How to reset its self

### ISSUE THREAD

**Issue by lovedota** [speedskater/babel-plugin-rewire#119]
Hi @speedskater 

Hi I have a code like this

``` js
let count = 1;

export default {
    increase() {
        count += 1;
    },
    
    decrease() {
        count -= 1;
    },
    
    get count() {
        return count;
    } 
};
```
in test i want to reset this object in everytime it get. How can i do it ? I know we can do it with *__set__('count')*, but for example, this single ton object has a lot of properties, using __set__ will be not good. I just want to completely reset this object.
``` js

import SingleTonUtils from './rewire-component/singleton-utils';

 describe('SingleTonObject', () => {
         beforeEach(() => {
            SingleTonUtils.__Reset__();    
        });

        it('Could increase value', () => {
            SingleTonUtils.increase();
            expect(SingleTonUtils.count).to.equal(2);
        });

        it('Could decrease value', () => {
            SingleTonUtils.decrease();
            expect(SingleTonUtils.count).to.equal(0);
        });
    });
```

**Comment by speedskater** [comment]
@lovedota 
Sorry for the late reply and thank you for reporting the issue. I think supporting your use case is not trivial, as it would imply executing the module multiple times. Although this is the case for the traditional rewire project, I think this is not feasible in an es2015 context. 
The reason is that es2015 modules can have cyclic dependencies as well can be referenced by other modules as well, which may rely on the fact that the module is executed exactly once.
Maybe a factory pattern for the object or an explicit reset function could solve your problem.
