### ISSUE TITLE
spy a function from a required module

### ISSUE THREAD

**Issue by bsr203** [speedskater/babel-plugin-rewire#19]
I had raised this issue originally here https://github.com/prometheusresearch/webtest/issues/7

But, I found that the test work fine if I don't use babel-rewire

Basically, just trying to spy on a dependent function like

dependency.js
--
```
/** @module dependency */

'use strict';

/** Does some stuff. */
export function baz(qux) {
    return qux.toLowerCase();
}

/** Does other stuff. */
export function foo(bar) {
    return bar.toUpperCase();
}
```
main.js
--
```
/** @module main */

'use strict';

import {foo} from './dependency';

/** Executes the module. */
export function run() {
    foo('bar');
}
```
main.spec.js
--
```
/* global beforeEach, describe, expect, it, spyOn */

'use strict';

var dependency = require('../dependency');

import {run} from '../main';

describe('Main', function() {
    beforeEach(function() {
        spyOn(dependency, 'foo');
    });

    it('calls dependency\'s foo:', function() {
        run();
        expect(dependency.foo).toHaveBeenCalledWith('bar');
    });
});
```

webpack conf

```
loaders: [
      {
          test: /\.js$/,
           // loaders: ['babel?optional[]=runtime&stage=0&plugins=rewire'],
           loaders: ['babel?optional[]=runtime&stage=0'],
          exclude: /node_modules/
      }
    ]
  },
```

the test fails if `rewire` enabled in the above config.

**Comment by speedskater** [comment]
Thanks for the detailed bug report. I will have a look at it.

**Comment by speedskater** [comment]
The issue you have reported is actually the correct behaviour. The reason is that foo is already resolved and assigned to another variable for the Main Module before you set the spy on the export foo of dependency.

But there is a working solution which should work for you. This solution rewires the foo import of the Main module with a spy function (could as well be a jasmine spy function).
I have added a sample to the unit  tests of babel-plugin-rewire. You could find the sample here:
https://github.com/speedskater/babel-plugin-rewire/blob/master/samples/issue19/sample.js

Please let me know if this solution is okay for you?

**Comment by bsr203** [comment]
it works great.. thanks for your support.
