### ISSUE TITLE
Possible to remove/extract jsx/react dependencies?

### ISSUE THREAD

**Issue by kellyselden** [speedskater/babel-plugin-rewire#97]
I was using 1.0.0-beta-3 on a few node/babel server apps. When I updated to 1.0.0-beta-5, I noticed all the new jsx and react dependencies. Would it be possible to move them to a dependent project, like "babel-plugin-rewire-react", as they aren't required for babel mocking?

**Comment by speedskater** [comment]
@kellyselden at the current state I would prefer to leave the dependency babel-plugin-syntax-jsx as a peer dependency of the plugin (it is the only required react/jsx runtime depenendency). The reason is that without this dependency rewiring code containing jsx statements does not work at all. 

See https://github.com/speedskater/babel-plugin-rewire/issues/82 for further details.

Theoretically it would be possible to change the structure to a more pluggable version. For the time beeing I think that this would make the plugin a bit overengineered. 

I hope this is okay for you or does jsx support causes you any direct troubles?

**Comment by boneskull** [comment]
I also would like to see `babel-plugin-syntax-jsx` removed as a peer dependency, as it's perfectly reasonable to use this module without React.  Besides, if you're using JSX, wouldn't you install that module *anyway*?

**Comment by speedskater** [comment]
@boneskull, @kellyselden I will have a further look if it is possible to remove the peer dependency.

**Comment by kellyselden** [comment]
@speedskater Awesome thank you!

**Comment by speedskater** [comment]
@kellyselden, @boneskull I left the react, jsx dependencies as dev dependencies but removed them as a peer depedency. Therefore the plugin itself provides the needed behavior without polluting your existing projects.

**Comment by boneskull** [comment]
@speedskater Thanks!  :clap:
